package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"
	"go-flight-tracker/graph/model"
)

// Aircrafts is the resolver for the aircrafts field.
func (r *queryResolver) Aircrafts(ctx context.Context, filter *model.FlightFilter) ([]*model.Aircraft, error) {
	return filterAircrafts(r.Store.GetAll(), filter), nil
}

// Aircraft is the resolver for the aircraft field.
func (r *queryResolver) Aircraft(ctx context.Context, icao24 string) (*model.Aircraft, error) {
	aircraft, exists := r.Store.GetByICAO(icao24)
	if !exists {
		return nil, fmt.Errorf("aircraft not found")
	}
	return mapToModel(aircraft), nil
}

// AircraftPhotos is the resolver for the aircraftPhotos field.
func (r *queryResolver) AircraftPhotos(ctx context.Context, icao24 string) ([]*model.AircraftPhoto, error) {
	if r.PhotosService == nil {
		return []*model.AircraftPhoto{}, nil
	}

	photos, err := r.PhotosService.ByICAO(ctx, icao24)
	if err != nil || len(photos) == 0 {
		return []*model.AircraftPhoto{}, nil
	}

	out := make([]*model.AircraftPhoto, 0, len(photos))
	for _, p := range photos {
		photographer := p.Photographer
		link := p.Link
		out = append(out, &model.AircraftPhoto{
			ID:           p.ID,
			ThumbnailURL: p.ThumbnailURL,
			URL:          p.URL,
			Photographer: &photographer,
			Link:         &link,
		})
	}
	return out, nil
}

// FlightUpdated is the resolver for the flightUpdated field.
func (r *subscriptionResolver) FlightUpdated(ctx context.Context, filter *model.FlightFilter) (<-chan []*model.Aircraft, error) {
	out := make(chan []*model.Aircraft)
	redisChan, err := r.RedisClient.SubscribeAircrafts(ctx)
	if err != nil {
		return out, err
	}
	go func() {
		defer close(out)

		for {
			select {
			case <-ctx.Done():
				return
			case aircrafts, ok := <-redisChan:
				if !ok {
					return
				}
				out <- filterAircrafts(aircrafts, filter)
			}
		}
	}()
	return out, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
