type Aircraft {
  icao24: String!
  callsign: String!
  originCountry: String!
  longitude: Float
  latitude: Float
  baroAltitude: Float
  onGround: Boolean!
  velocity: Float
  trueTrack: Float
  verticalRate: Float
  squawk: String
  spi: Boolean!
  positionSource: Int!
  category: Int!
  lastPositionUpdate: Int
  lastContact: Int
}

input FlightFilter {
  originCountry: String
  minAltitude: Float
  maxAltitude: Float
  callsignPrefix: String
}

type Query {
  #Map search
  aircrafts: [Aircraft!]!
  
  #Search for a specific aircraft by ICAO24
  aircraft(icao24: String!): Aircraft
}

type Subscription {
  #Subscribe to flight updates
  flightUpdated(filter: FlightFilter): [Aircraft!]!
}