package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"
	"go-flight-tracker/graph/model"
	"go-flight-tracker/internal/flight"
)

// Aircrafts is the resolver for the aircrafts field.
func (r *queryResolver) Aircrafts(ctx context.Context) ([]*model.Aircraft, error) {
	aircrafts := r.Store.GetAll()
	models := make([]*model.Aircraft, 0, len(aircrafts))
	for _, aircraft := range aircrafts {
		models = append(models, mapToModel(aircraft))
	}
	return models, nil
}

// Aircraft is the resolver for the aircraft field.
func (r *queryResolver) Aircraft(ctx context.Context, icao24 string) (*model.Aircraft, error) {
	aircraft, exists := r.Store.GetByICAO(icao24)
	if !exists {
		return nil, fmt.Errorf("aircraft not found")
	}
	return mapToModel(aircraft), nil
}

// FlightUpdated is the resolver for the flightUpdated field.
func (r *subscriptionResolver) FlightUpdated(ctx context.Context, filter *model.FlightFilter) (<-chan []*model.Aircraft, error) {
	out := make(chan []*model.Aircraft)
	redisChan, err := r.RedisClient.SubscribeAircrafts(ctx)
	if err != nil {
		return out, err
	}
	go func() {
		defer close(out)

		for {
			select {
			case <-ctx.Done():
				return
			case aircrafts, ok := <-redisChan:
				if !ok {
					return
				}
				models := make([]*model.Aircraft, 0, len(aircrafts))
				for _, aircraft := range aircrafts {
					models = append(models, mapToModel(aircraft))
				}
				out <- models
			}
		}
	}()
	return out, nil
}

func mapToModel(a *flight.Aircraft) *model.Aircraft {
	if a == nil {
		return nil
	}
	lastPos := int32(a.TimePosition)
	lastContact := int32(a.LastContact)
	squawk := a.Squawk

	return &model.Aircraft{
		Icao24:             a.Icao24,
		Callsign:           a.Callsign,
		OriginCountry:      a.OriginCountry,
		Longitude:          &a.Longitude,
		Latitude:           &a.Latitude,
		BaroAltitude:       &a.BaroAltitude,
		OnGround:           a.OnGround,
		Velocity:           &a.Velocity,
		TrueTrack:          &a.TrueTrack,
		VerticalRate:       &a.VerticalRate,
		Squawk:             &squawk,
		Spi:                a.Spi,
		PositionSource:     int32(a.PositionSource),
		Category:           int32(a.Category),
		LastPositionUpdate: &lastPos,
		LastContact:        &lastContact,
	}
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }
type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
*/
