// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Aircraft struct {
	Icao24             string   `json:"icao24"`
	Callsign           string   `json:"callsign"`
	OriginCountry      string   `json:"originCountry"`
	Longitude          *float64 `json:"longitude,omitempty"`
	Latitude           *float64 `json:"latitude,omitempty"`
	BaroAltitude       *float64 `json:"baroAltitude,omitempty"`
	OnGround           bool     `json:"onGround"`
	Velocity           *float64 `json:"velocity,omitempty"`
	TrueTrack          *float64 `json:"trueTrack,omitempty"`
	VerticalRate       *float64 `json:"verticalRate,omitempty"`
	Squawk             *string  `json:"squawk,omitempty"`
	Spi                bool     `json:"spi"`
	PositionSource     int32    `json:"positionSource"`
	Category           int32    `json:"category"`
	LastPositionUpdate *int32   `json:"lastPositionUpdate,omitempty"`
	LastContact        *int32   `json:"lastContact,omitempty"`
}

type AircraftPhoto struct {
	ID           string  `json:"id"`
	ThumbnailURL string  `json:"thumbnailUrl"`
	URL          string  `json:"url"`
	Photographer *string `json:"photographer,omitempty"`
	Link         *string `json:"link,omitempty"`
}

type FlightFilter struct {
	OriginCountry  *string  `json:"originCountry,omitempty"`
	MinAltitude    *float64 `json:"minAltitude,omitempty"`
	MaxAltitude    *float64 `json:"maxAltitude,omitempty"`
	CallsignPrefix *string  `json:"callsignPrefix,omitempty"`
	Lamin          *float64 `json:"lamin,omitempty"`
	Lomin          *float64 `json:"lomin,omitempty"`
	Lamax          *float64 `json:"lamax,omitempty"`
	Lomax          *float64 `json:"lomax,omitempty"`
}

type Query struct {
}

type Subscription struct {
}
